#pragma once
#include "../../Common/DllInterface.h"

#ifdef _WIN32
#include <Windows.h>
#include <gl/gl.h>
#include <gl/glext.h>
extern PGN_DLL_INTERFACE PFNGLACTIVETEXTUREPROC						glActiveTexture;
extern PGN_DLL_INTERFACE PFNGLATTACHSHADERPROC						glAttachShader;
extern PGN_DLL_INTERFACE PFNGLBINDATTRIBLOCATIONPROC				glBindAttribLocation;
extern PGN_DLL_INTERFACE PFNGLBINDBUFFERPROC						glBindBuffer;
extern PGN_DLL_INTERFACE PFNGLBINDBUFFERBASEPROC					glBindBufferBase;
extern PGN_DLL_INTERFACE PFNGLBINDBUFFERRANGEPROC					glBindBufferRange;
extern PGN_DLL_INTERFACE PFNGLBINDFRAMEBUFFERPROC					glBindFramebuffer;
extern PGN_DLL_INTERFACE PFNGLBINDRENDERBUFFERPROC					glBindRenderbuffer;
extern PGN_DLL_INTERFACE PFNGLBINDSAMPLERPROC						glBindSampler;
extern PGN_DLL_INTERFACE PFNGLBLENDCOLORPROC						glBlendColor;
extern PGN_DLL_INTERFACE PFNGLBLENDEQUATIONSEPARATEPROC				glBlendEquationSeparate;
extern PGN_DLL_INTERFACE PFNGLBLENDEQUATIONSEPARATEIPROC			glBlendEquationSeparatei;
extern PGN_DLL_INTERFACE PFNGLBLENDFUNCSEPARATEPROC					glBlendFuncSeparate;
extern PGN_DLL_INTERFACE PFNGLBLENDFUNCSEPARATEIPROC				glBlendFuncSeparatei;
extern PGN_DLL_INTERFACE PFNGLBLITFRAMEBUFFERPROC					glBlitFramebuffer;
extern PGN_DLL_INTERFACE PFNGLBUFFERDATAPROC						glBufferData;
extern PGN_DLL_INTERFACE PFNGLBUFFERSUBDATAPROC						glBufferSubData;
extern PGN_DLL_INTERFACE PFNGLCHECKFRAMEBUFFERSTATUSPROC			glCheckFramebufferStatus;
extern PGN_DLL_INTERFACE PFNGLCLEARDEPTHFPROC						glClearDepthf;
extern PGN_DLL_INTERFACE PFNGLCOMPILESHADERPROC						glCompileShader;
extern PGN_DLL_INTERFACE PFNGLCOMPRESSEDTEXIMAGE2DPROC				glCompressedTexImage2D;
extern PGN_DLL_INTERFACE PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC			glCompressedTexSubImage2D;
extern PGN_DLL_INTERFACE PFNGLCREATEPROGRAMPROC						glCreateProgram;
extern PGN_DLL_INTERFACE PFNGLCREATESHADERPROC						glCreateShader;
extern PGN_DLL_INTERFACE PFNGLDELETEBUFFERSPROC						glDeleteBuffers;
extern PGN_DLL_INTERFACE PFNGLDELETEFRAMEBUFFERSPROC				glDeleteFramebuffers;
extern PGN_DLL_INTERFACE PFNGLDELETEPROGRAMPROC						glDeleteProgram;
extern PGN_DLL_INTERFACE PFNGLDELETERENDERBUFFERSPROC				glDeleteRenderbuffers;
extern PGN_DLL_INTERFACE PFNGLDELETESAMPLERSPROC					glDeleteSamplers;
extern PGN_DLL_INTERFACE PFNGLDELETESHADERPROC						glDeleteShader;
extern PGN_DLL_INTERFACE PFNGLDELETESYNCPROC						glDeleteSync;
extern PGN_DLL_INTERFACE PFNGLDEPTHRANGEFPROC						glDepthRangef;
extern PGN_DLL_INTERFACE PFNGLDETACHSHADERPROC						glDetachShader;
extern PGN_DLL_INTERFACE PFNGLDISABLEIPROC							glDisablei;
extern PGN_DLL_INTERFACE PFNGLDISABLEVERTEXATTRIBARRAYPROC			glDisableVertexAttribArray;
extern PGN_DLL_INTERFACE PFNGLDRAWBUFFERSPROC						glDrawBuffers;
extern PGN_DLL_INTERFACE PFNGLDRAWELEMENTSINSTANCEDPROC				glDrawElementsInstanced;
extern PGN_DLL_INTERFACE PFNGLENABLEIPROC							glEnablei;
extern PGN_DLL_INTERFACE PFNGLENABLEVERTEXATTRIBARRAYPROC			glEnableVertexAttribArray;
extern PGN_DLL_INTERFACE PFNGLFENCESYNCPROC							glFenceSync;
extern PGN_DLL_INTERFACE PFNGLFRAMEBUFFERRENDERBUFFERPROC			glFramebufferRenderbuffer;
extern PGN_DLL_INTERFACE PFNGLFRAMEBUFFERTEXTURE2DPROC				glFramebufferTexture2D;
extern PGN_DLL_INTERFACE PFNGLGENBUFFERSPROC						glGenBuffers;
extern PGN_DLL_INTERFACE PFNGLGENFRAMEBUFFERSPROC					glGenFramebuffers;
extern PGN_DLL_INTERFACE PFNGLGENRENDERBUFFERSPROC					glGenRenderbuffers;
extern PGN_DLL_INTERFACE PFNGLGENSAMPLERSPROC						glGenSamplers;
extern PGN_DLL_INTERFACE PFNGLGETACTIVEATTRIBPROC					glGetActiveAttrib;
extern PGN_DLL_INTERFACE PFNGLGETACTIVEUNIFORMPROC					glGetActiveUniform;
extern PGN_DLL_INTERFACE PFNGLGETACTIVEUNIFORMBLOCKIVPROC			glGetActiveUniformBlockiv;
extern PGN_DLL_INTERFACE PFNGLGETACTIVEUNIFORMBLOCKNAMEPROC			glGetActiveUniformBlockName;
extern PGN_DLL_INTERFACE PFNGLGETATTRIBLOCATIONPROC					glGetAttribLocation;
extern PGN_DLL_INTERFACE PFNGLGETPROGRAMBINARYPROC					glGetProgramBinary;
extern PGN_DLL_INTERFACE PFNGLGETPROGRAMINFOLOGPROC					glGetProgramInfoLog;
extern PGN_DLL_INTERFACE PFNGLGETPROGRAMIVPROC						glGetProgramiv;
extern PGN_DLL_INTERFACE PFNGLGETSHADERINFOLOGPROC					glGetShaderInfoLog;
extern PGN_DLL_INTERFACE PFNGLGETSHADERIVPROC						glGetShaderiv;
extern PGN_DLL_INTERFACE PFNGLGETSHADERSOURCEPROC					glGetShaderSource;
extern PGN_DLL_INTERFACE PFNGLGETSTRINGIPROC						glGetStringi;
extern PGN_DLL_INTERFACE PFNGLGETSYNCIVPROC							glGetSynciv;
extern PGN_DLL_INTERFACE PFNGLGETUNIFORMBLOCKINDEXPROC				glGetUniformBlockIndex;
extern PGN_DLL_INTERFACE PFNGLGETUNIFORMLOCATIONPROC				glGetUniformLocation;
extern PGN_DLL_INTERFACE PFNGLLINKPROGRAMPROC						glLinkProgram;
extern PGN_DLL_INTERFACE PFNGLMAPBUFFERRANGEPROC					glMapBufferRange;
extern PGN_DLL_INTERFACE PFNGLPROGRAMBINARYPROC						glProgramBinary;
extern PGN_DLL_INTERFACE PFNGLPROGRAMPARAMETERIPROC					glProgramParameteri;
extern PGN_DLL_INTERFACE PFNGLRENDERBUFFERSTORAGEPROC				glRenderbufferStorage;
extern PGN_DLL_INTERFACE PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC	glRenderbufferStorageMultisample;
extern PGN_DLL_INTERFACE PFNGLSAMPLECOVERAGEPROC					glSampleCoverage;
extern PGN_DLL_INTERFACE PFNGLSAMPLERPARAMETERFPROC					glSamplerParameterf;
extern PGN_DLL_INTERFACE PFNGLSAMPLERPARAMETERIPROC					glSamplerParameteri;
extern PGN_DLL_INTERFACE PFNGLSHADERSOURCEPROC						glShaderSource;
extern PGN_DLL_INTERFACE PFNGLSTENCILFUNCSEPARATEPROC				glStencilFuncSeparate;
extern PGN_DLL_INTERFACE PFNGLSTENCILOPSEPARATEPROC					glStencilOpSeparate;
extern PGN_DLL_INTERFACE PFNGLUNIFORM1IPROC							glUniform1i;
extern PGN_DLL_INTERFACE PFNGLUNIFORMBLOCKBINDINGPROC				glUniformBlockBinding;
extern PGN_DLL_INTERFACE PFNGLUNMAPBUFFERPROC						glUnmapBuffer;
extern PGN_DLL_INTERFACE PFNGLUSEPROGRAMPROC						glUseProgram;
extern PGN_DLL_INTERFACE PFNGLVERTEXATTRIBDIVISORPROC				glVertexAttribDivisor;
extern PGN_DLL_INTERFACE PFNGLVERTEXATTRIBIPOINTERPROC				glVertexAttribIPointer;
extern PGN_DLL_INTERFACE PFNGLVERTEXATTRIBPOINTERPROC				glVertexAttribPointer;
#endif

#ifdef __APPLE__
#include <TargetConditionals.h>
#ifdef TARGET_OS_IPHONE
#import <OpenGLES/ES3/gl.h>
#import <OpenGLES/ES3/glext.h>
// 只为能编译通过
#define GL_COMPRESSED_RGB_S3TC_DXT1_EXT                   0x83F0
#define GL_COMPRESSED_RGBA_S3TC_DXT1_EXT                  0x83F1
#define GL_COMPRESSED_RGBA_S3TC_DXT3_EXT                  0x83F2
#define GL_COMPRESSED_RGBA_S3TC_DXT5_EXT                  0x83F3
#endif
#endif

namespace pgn {

struct GLInfo
{
	const unsigned char* vendor;
	const unsigned char* renderer;
	const unsigned char* version;
	const unsigned char* shadingLanguageVersion;
	const unsigned char** extensions;
	int numExt;

	bool EXT_texture_filter_anisotropic;
};

PGN_DLL_INTERFACE GLInfo* getGLInfo();
PGN_DLL_INTERFACE char* getGLSLVersionDecl();

}	// namespace pgn
