#include <gxm/texture_defs.h>

const unsigned samplerClearMask = SCE_GXM_PDS_DOUTT0_MIPMAPCLAMP_CLRMSK
								& SCE_GXM_PDS_DOUTT0_MINFILTER_CLRMSK
								& SCE_GXM_PDS_DOUTT0_MIPFILTER_CLRMSK
								& SCE_GXM_PDS_DOUTT0_MAGFILTER_CLRMSK
								& SCE_GXM_PDS_DOUTT0_UADDRMODE_CLRMSK
								& SCE_GXM_PDS_DOUTT0_VADDRMODE_CLRMSK;
