
struct EnvDesc;

enum PassEnum
{
	Z_PRE_PASS,
	GEOMETRY_PASS,
	LIGHT_VOLUME_BACK_FACE_PASS_1,
	LIGHT_VOLUME_FRONT_FACE_PASS_1,
	LIGHT_INDEXING_PASS_1,
	LIGHT_VOLUME_BACK_FACE_PASS_2,
	LIGHT_VOLUME_FRONT_FACE_PASS_2,
	LIGHT_INDEXING_PASS_2,
	LIGHT_VOLUME_BACK_FACE_PASS_3,
	LIGHT_VOLUME_FRONT_FACE_PASS_3,
	LIGHT_INDEXING_PASS_3,
	LIGHT_VOLUME_BACK_FACE_PASS_4,
	LIGHT_VOLUME_FRONT_FACE_PASS_4,
	LIGHT_INDEXING_PASS_4,
	LIGHTING_PASS,
	FORWARD_SHADING_PASS,

	numPasses
};

extern EnvDesc* envDescs[numPasses];
